default:
  #tasks: !expr readRDS(file = "data/wissel2023/task_list.rds") # All omics (<2K features)

  # select task from .rds file for efs
  #task: !expr readRDS(file = "data/wissel2023/task_list.rds")$gex # Wissel GEX (2K features)
  #task: !expr readRDS(file = "data/osipov2024/task_list.rds")$snv # SNV - Osipov (274 features)
  task: !expr readRDS(file = "data/wissel2023/gex_task.rds") # Wissel GEX (~20K features)
  results_dir: "sensitivity_analysis" # also: "test"
  dataset_id: "wissel2023" # also: "osipov2024"
  logging:
    bbotk_log: !expr lgr::get_logger("bbotk")$set_threshold("warn")
    mlr3_log: !expr lgr::get_logger("mlr3")$set_threshold("info")
  workers: 10 # for parallelization
  efs:
    store_bmr: FALSE
    repeats: 100 # how many subsamples per learner
    ratio: 0.8 # % of training data for tuning/feature selection
  learner_params:
    n_trees: 500 # RSFs
    nrounds: 500 # xgboost, glmboost and cv_coxboost
    folds: 5 # for inner resampling/tuning
    evals: 25 # random search evaluations (glmboost)
    eta: 0.1 # learning rate
    nrounds_early: 42 # early stopping rounds (for xgboost, should be < nrounds)
    max_depth: 6 # for xgboost
