default:
  overwrite: TRUE # whether to overwrite the efs result on the disk
  verbose: 0 # 0: don't print anything, 1: print some info, timings, etc.
  use: # which learner to use in the benchmark (all by default)
    RSF: TRUE
    XGBoost: TRUE
    GLMBoost: TRUE
    CoxBoost: TRUE
    CoxLasso: TRUE
  logging:
    bbotk_log: !expr lgr::get_logger("bbotk")$set_threshold("warn")
    mlr3_log: !expr lgr::get_logger("mlr3")$set_threshold("warn")
  workers: 20 # for parallelization
  efs:
    store_bmr: FALSE
    repeats: 100 # how many subsamples per learner
    ratio: 0.8 # % of training data for tuning/feature selection
  learner_params:
    n_trees: 500 # RSFs
    nrounds: 500 # xgboost, glmboost and cv_coxboost
    folds: 5 # for inner resampling/tuning
    evals: 25 # random search evaluations (glmboost)
    eta: 0.1 # learning rate (xgboost, glmboost)
    nrounds_early: 42 # early stopping rounds (xgboost, should be < nrounds)
    max_depth: 6 # xgboost
